# Generated by Django 5.0.1 on 2024-04-12 11:37

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=200)),
                ('land_mark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('pending', 'pending'), ('partially_paid', 'partially_paid')], max_length=20)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('int_due', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('pri_due', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('due_date', models.DateTimeField()),
                ('paid_date', models.DateField(null=True)),
                ('nth_due', models.PositiveIntegerField()),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('NEFT', 'NEFT'), ('UPI', 'UPI')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_grams', models.IntegerField()),
                ('weight_milligrams', models.IntegerField()),
                ('pic', models.ImageField(upload_to='Property/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('pic', models.ImageField(null=True, upload_to='Customer/')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.address')),
                ('properties', models.ManyToManyField(related_name='customer', to='home.property')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('loan_repaid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('intrest_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('no_of_dues', models.IntegerField()),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('dues', models.ManyToManyField(related_name='Dues_of_Loan', to='home.due')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
        ),
        migrations.AddField(
            model_name='due',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.loan'),
        ),
    ]
